#!/bin/bash

print_color () { tput setab 7; tput setaf 0; echo "$1"; tput sgr0; }

# Check all required CLIs are available
dependencies=( wget git unzip )
for dependency in "${dependencies[@]}"; do
  command -v $dependency >/dev/null 2>&1 || apt-get install $dependency
done


####################################
# PLUGIN INSTALLATION & ACTIVATION #
####################################

__DIRNAME="hgnm-wp-dev"
WP_DIR="app/public"

# Advanced Custom Fields Pro
print_color "Installing Advanced Custom Fields Pro plugin..."
wget -O "$WP_DIR/wp-content/plugins/acf-pro.zip" "http://connect.advancedcustomfields.com/index.php?p=pro&a=download&k=b3JkZXJfaWQ9NjQzMTJ8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE1LTA5LTE2IDAzOjE4OjEy"
if [[ -f "$WP_DIR/wp-content/plugins/acf-pro.zip" ]]; then
  wp plugin install "$WP_DIR/wp-content/plugins/acf-pro.zip" --activate
  rm "$WP_DIR/wp-content/plugins/acf-pro.zip"
else
  echo "Can’t find file: $WP_DIR/wp-content/plugins/acf-pro.zip. Fatal error…"
  exit 1
fi

# WordPress Importer
print_color "Installing WordPress Importer plugin..."
wp plugin install wordpress-importer --activate


###################################
# THEME INSTALLATION & ACTIVATION #
###################################

# Set remote URL
THEME_REMOTE_URL="https://github.com/HGNM/hgnm-2014.git"
THEME_LOCAL_DIR="$WP_DIR/wp-content/themes/hgnm-2014"

# Install & activate hgnm-2014 theme
print_color "Installing hgnm-2014 WordPress theme..."
git clone $THEME_REMOTE_URL $THEME_LOCAL_DIR
if [ -d $THEME_LOCAL_DIR ]; then
  wp theme activate hgnm-2014
else
  echo "Can’t find directory: $THEME_LOCAL_DIR. Fatal error…"
  exit 1
fi


#############################
# POPULATE DATABASE CONTENT #
#############################

# Clean default generated content
print_color "Deleting generic WordPress content..."
wp post delete 1 --force # Delete ‘Hello world!’ post
wp post delete 2 --force # Delete sample page
# Import exported XML from hgnm.org
HGNM_CONTENT="$__DIRNAME/hgnm-export.xml"
print_color "Importing hgnm.org content..."
if [[ -f $HGNM_CONTENT ]]; then
  wp import $HGNM_CONTENT --authors=create
else
  echo "Can’t find file: $HGNM_CONTENT. Fatal error…"
  exit 1
fi
